// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var NoteParser$ReactTemplate = require("../NoteParser/NoteParser.bs.js");

function build() {
  return (function (param) {
      return $$Array.map(NoteParser$ReactTemplate.toNoteWithOctave, param);
    });
}

exports.build = build;
/* NoteParser-ReactTemplate Not a pure module */
