// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Caml_int32 = require("bs-platform/lib/js/caml_int32.js");
var CamlinternalOO = require("bs-platform/lib/js/camlinternalOO.js");
var Note$ReactTemplate = require("../Note/Note.bs.js");

function toCents(param) {
  var base = Note$ReactTemplate.toCents(param[0]);
  var octaveShift = Caml_int32.imul(param[1], 1200);
  return base + octaveShift | 0;
}

function toHertz(param) {
  var semitones = Note$ReactTemplate.toSemitones(param[0]);
  var octaveFactor = Math.pow(2.0, param[1]);
  return semitones * 440.0 * octaveFactor;
}

var class_tables = [
  0,
  0,
  0
];

function fromString() {
  if (!class_tables[0]) {
    var $$class = CamlinternalOO.create_table(0);
    var env_init = function () {
      return CamlinternalOO.create_object_opt(0, $$class);
    };
    CamlinternalOO.init_class($$class);
    class_tables[0] = env_init;
  }
  return Curry._1(class_tables[0], 0);
}

exports.toCents = toCents;
exports.toHertz = toHertz;
exports.fromString = fromString;
/* No side effect */
